Vagrant.configure("2") do |config|
  config.vm.define "u1" do |u1|		
    u1.vm.box = "hashicorp/bionic64"
    u1.vm.network "private_network", ip: "192.168.33.10"
  end 

  config.vm.define "u2" do |u2|
    u2.vm.box = "hashicorp/bionic64"
    u2.vm.network "private_network", ip: "192.168.33.11" 
  end
end
